/obj/item/storage/bag/garment/chief_medical/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck(src)
	new /obj/item/clothing/under/rank/medical/chief_medical_officer/turtleneck/skirt(src)

/obj/item/storage/bag/garment/hop/PopulateContents()
	. = ..()
	new /obj/item/clothing/glasses/hud/civilian/sunglasses(src)

/obj/item/storage/bag/garment/hos/PopulateContents()
	. = ..()
	new /obj/item/clothing/under/rank/security/viro/head_of_security/viro(src)
	new /obj/item/clothing/under/rank/security/viro/head_of_security/skirt(src)
	new /obj/item/clothing/under/rank/security/viro/head_of_security/formal(src)
	new /obj/item/clothing/under/rank/security/viro/head_of_security/formal/skirt(src)
	new /obj/item/clothing/suit/armor/hos/viro/trenchcoat/winter(src)
	new /obj/item/clothing/suit/armor/hos/viro(src)
	new /obj/item/clothing/suit/armor/hos/viro/vest(src)
	new /obj/item/clothing/head/helmet/sec/viro/hos(src)
	new /obj/item/clothing/under/rank/security/head_of_security/turtleneck/red(src)
	new /obj/item/clothing/under/rank/security/head_of_security/turtleneck/red/skirt(src)
	new /obj/item/clothing/under/rank/security/head_of_security/redsec(src)
	new /obj/item/clothing/shoes/jackboots/sec/redsec(src)
	new /obj/item/clothing/head/hos_kepi(src)
	new /obj/item/clothing/head/hats/warden/drill/hos(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/alt/roselia(src)
	new	/obj/item/clothing/head/hats/hos/elofy(src)
	new	/obj/item/clothing/suit/armor/hos/elofy(src)
	new	/obj/item/clothing/gloves/elofy(src)
	new	/obj/item/clothing/shoes/jackboots/elofy(src)
	new	/obj/item/clothing/head/playbunnyears/hos(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/bunnysuit(src)
	new	/obj/item/clothing/suit/armor/hos_tailcoat(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/suit/red(src)
	new /obj/item/clothing/head/hats/hos/beret/navyhos(src)
	new /obj/item/clothing/suit/jacket/hos/blue(src)
	new /obj/item/clothing/neck/mantle/hosmantle(src)

/obj/item/storage/bag/garment/warden/PopulateContents()
	. = ..()
	for(var/obj/item/clothing/gloves/kaza_ruk/sec/original_gloves in src)
		if(original_gloves.type == /obj/item/clothing/gloves/kaza_ruk/sec)
			qdel(original_gloves)
	new /obj/item/clothing/under/rank/security/viro/warden/skirt/(src)
	new /obj/item/clothing/under/rank/security/viro/warden/(src)
	new /obj/item/clothing/under/rank/security/viro/warden/formal/(src)
	new /obj/item/clothing/under/rank/security/viro/warden/formal/skirt(src)
	new /obj/item/clothing/suit/armor/vest/viro/warden/wintercoat(src)
	new /obj/item/clothing/suit/armor/vest/viro/warden/alt(src)
	new /obj/item/clothing/suit/armor/vest/viro/warden(src)
	new /obj/item/clothing/under/rank/security/warden/battledress/red(src)
	new /obj/item/clothing/under/rank/security/warden/turtleneck/red(src)
	new /obj/item/clothing/under/rank/security/warden/turtleneck/red/skirt(src)
	new /obj/item/clothing/under/rank/security/warden/suit/red(src)






