GLOBAL_LIST_INIT(arcade_prize_pool_toy, list(
	/obj/item/ammo_box/foambox = 100,
	/obj/item/banhammer = 10,
	/obj/item/camera = 50,
	/obj/item/canvas/drawingtablet = 50,
	/obj/item/clothing/glasses/fake_sunglasses = 10,
	/obj/item/clothing/glasses/welding/steampunk_goggles = 25, //Donator item, but these are too cool.
	list(
		/obj/item/clothing/gloves/boxing = 1,
		/obj/item/clothing/gloves/boxing/blue = 1,
		/obj/item/clothing/gloves/boxing/green = 1,
		/obj/item/clothing/gloves/boxing/yellow = 1,
	) = 25,
	list(
		/obj/item/clothing/head/collectable/beret = 1,
		/obj/item/clothing/head/collectable/captain = 1,
		/obj/item/clothing/head/collectable/chef = 1,
		/obj/item/clothing/head/collectable/flatcap = 1,
		/obj/item/clothing/head/collectable/hardhat = 1,
		/obj/item/clothing/head/collectable/hop = 1,
		/obj/item/clothing/head/collectable/hos = 1,
		/obj/item/clothing/head/collectable/kitty = 1,
		/obj/item/clothing/head/collectable/paper = 1,
		/obj/item/clothing/head/collectable/petehat = 1,
		/obj/item/clothing/head/collectable/pirate = 1,
		/obj/item/clothing/head/collectable/police = 1,
		/obj/item/clothing/head/collectable/rabbitears = 1,
		/obj/item/clothing/head/collectable/slime = 1,
		/obj/item/clothing/head/collectable/swat = 1,
		/obj/item/clothing/head/collectable/thunderdome = 1,
		/obj/item/clothing/head/collectable/tophat = 1,
		/obj/item/clothing/head/collectable/welding = 1,
		/obj/item/clothing/head/collectable/wizard = 1,
		/obj/item/clothing/head/collectable/xenom = 1
	) = 200,
	list(
		/obj/item/clothing/head/costume/allies = 1,
		/obj/item/clothing/head/costume/canada = 1,
		/obj/item/clothing/head/costume/powdered_wig = 1,
		/obj/item/clothing/head/costume/santa = 1,
		/obj/item/clothing/head/costume/snakeeater = 1,
		/obj/item/clothing/head/costume/sombrero/green = 1,
		/obj/item/clothing/head/helmet/toggleable/justice = 1,
		/obj/item/clothing/head/helmet/toggleable/justice/escape = 1,
		/obj/item/clothing/head/waldo = 1,
		/obj/item/clothing/mask/fakemoustache = 1,
		/obj/item/clothing/mask/joy = 1,
		/obj/item/clothing/neck/necklace/dope = 1,
		/obj/item/clothing/suit/toggle/rainbowcoat = 1, //Donator item, but it's too cool.
	) = 50,
	/obj/item/clothing/mask/facehugger/toy = 25,
	list(
		/obj/item/clothing/mask/gondola = 1,
		/obj/item/clothing/mask/luchador = 1,
		/obj/item/clothing/mask/luchador/rudos = 1,
		/obj/item/clothing/mask/luchador/tecnicos = 1
	) = 25,
	/obj/item/clothing/mask/whistle = 10,
	/obj/item/clothing/neck/link_scryer/loaded = 50,
	/obj/item/clothing/suit/hooded/flashsuit = 25,
	list(
		/obj/item/clothing/suit/hooded/wintercoat/skyrat/ratvar = 1,
		/obj/item/clothing/suit/hooded/wintercoat/skyrat/narsie = 1
	) = 25,
	/obj/item/etherealballdeployer = 5,
	/obj/item/fakeartefact = 25,
	/obj/item/firing_pin/clown = 5,
	/obj/item/stamp/cat = 5,
	/obj/item/storage/belt/champion = 5,
	/obj/item/storage/box/party_poppers = 50,
	/obj/item/surprise_egg = 100,
	/obj/item/toy/plush/goatplushie = 2,
))
