GLOBAL_LIST_INIT(rarity_loot, list(//rare: really good items - TODO: FIND THE NEW PATHS FROM THE COMMENTED PARTS
	/obj/item/aicard/aitater = 10,
	/obj/item/ammo_box/foambox/riot = 25,
	list(
		/obj/item/survivalcapsule = 100,
		/obj/item/survivalcapsule/luxury = 10,
		/obj/item/survivalcapsule/luxuryelite = 5,
		/obj/item/survivalcapsule/sauna = 5,
		/obj/item/survivalcapsule/bathroom = 1
	) = 25,
	/obj/item/table_clock = 25,
	/obj/item/storage/briefcase/coderbus = 10,
	/obj/item/analyzer/ranged = 1,
	list(
		/obj/item/autosurgeon/organ/nif/disposable = 10,
		/obj/item/autosurgeon/organ/nif = 1
	) = 1,
	/obj/item/beacon = 1,
	list(
		/obj/item/clothing/glasses/hud/ar/projector/diagnostic = 50,
		/obj/item/clothing/glasses/hud/ar/projector/health = 25,
		/obj/item/clothing/glasses/hud/ar/projector/meson = 100,
		/obj/item/clothing/glasses/hud/ar/projector/science = 25,
		/obj/item/clothing/glasses/hud/ar/projector/security = 10,
		/obj/item/clothing/glasses/hud/eyepatch/diagnostic = 50,
		/obj/item/clothing/glasses/hud/eyepatch/med = 25,
		/obj/item/clothing/glasses/hud/eyepatch/meson = 100,
		/obj/item/clothing/glasses/hud/eyepatch/sci = 25,
		/obj/item/clothing/glasses/hud/eyepatch/sec = 10,
		/obj/item/clothing/glasses/hud/diagnostic = 50,
		/obj/item/clothing/glasses/hud/health = 25,
		/obj/item/clothing/glasses/material/mining = 100,
		/obj/item/clothing/glasses/meson = 100,
		/obj/item/clothing/glasses/science = 25,
		/obj/item/clothing/glasses/hud/security = 10,
		/obj/item/clothing/glasses/hud/gun_permit = 25,
		/obj/item/clothing/glasses/hud/security/redsec = 5,
		/obj/item/clothing/glasses/meson/engine = 25,
		/obj/item/clothing/glasses/meson/engine/tray = 25,
		/obj/item/clothing/glasses/sunglasses/reagent = 1,
		/obj/item/clothing/glasses/sunglasses/chemical = 1,
		/obj/item/clothing/glasses/sunglasses/spy = 1
	) = 10,
	list(
		/obj/item/clothing/glasses/sunglasses = 10,
		/obj/item/clothing/glasses/sunglasses/big = 1
	) = 25,
	list(
		/obj/item/clothing/head/collectable/captain = 1,
		/obj/item/clothing/head/collectable/chef = 1,
		/obj/item/clothing/head/collectable/hardhat = 1,
		/obj/item/clothing/head/collectable/hop = 1,
		/obj/item/clothing/head/collectable/hos = 1,
		/obj/item/clothing/head/collectable/kitty = 1,
		/obj/item/clothing/head/collectable/paper = 1,
		/obj/item/clothing/head/collectable/petehat = 1,
		/obj/item/clothing/head/collectable/pirate = 1,
		/obj/item/clothing/head/collectable/police = 1,
		/obj/item/clothing/head/collectable/rabbitears = 1,
		/obj/item/clothing/head/collectable/slime = 1,
		/obj/item/clothing/head/collectable/swat = 1,
		/obj/item/clothing/head/collectable/thunderdome = 1,
		/obj/item/clothing/head/collectable/tophat = 1,
		/obj/item/clothing/head/collectable/welding = 1,
		/obj/item/clothing/head/collectable/wizard = 1,
		/obj/item/clothing/head/collectable/xenom = 1
	) = 50,
	/obj/item/clothing/mask/gas/sechailer = 10,
	/obj/item/clothing/suit/hooded/bloated_human = 5,
	list(
		/obj/item/construction/plumbing = 1,
		/obj/item/construction/plumbing/engineering = 1,
		/obj/item/construction/plumbing/mining = 1,
		/obj/item/construction/plumbing/service = 1,
		/obj/item/construction/rcd = 1,
		/obj/item/construction/rld = 10,
		/obj/item/construction/rtd = 10,
		/obj/item/pipe_dispenser = 1,
		/obj/item/rsf = 10,
		/obj/item/rsf/cookiesynth = 5,
		/obj/item/rwd/loaded = 10
	) = 20,
	/obj/item/cortical_cage = 5,
	/obj/item/detective_scanner = 15,
	list(
		/obj/item/dnainjector/chavmut = 10,
		/obj/item/dnainjector/clever = 1,
		/obj/item/dnainjector/clumsymut = 5,
		/obj/item/dnainjector/dwarf = 1,
		/obj/item/dnainjector/elvismut = 10,
		/obj/item/dnainjector/epimut = 5,
		/obj/item/dnainjector/gigantism = 1,
		/obj/item/dnainjector/glassesmut = 5,
		/obj/item/dnainjector/glow = 1,
		/obj/item/dnainjector/illiterate = 5,
		/obj/item/dnainjector/m2h = 5,
		/obj/item/dnainjector/piglatinmut = 5,
		/obj/item/dnainjector/stuttmut = 10,
		/obj/item/dnainjector/swedishmut = 10,
		/obj/item/dnainjector/timed/h2m = 1,
		/obj/item/dnainjector/tourmut = 1,
		/obj/item/dnainjector/twoleftfeet = 1,
		/obj/item/dnainjector/wackymut = 10,
		/obj/item/dnainjector/spastic = 1,
		/obj/item/dnainjector/paranoia = 1,
		/obj/item/dnainjector/coughmut = 1,
		/obj/item/dnainjector/antenna = 1
	) = 25,
	/obj/item/dog_bone = 5,
	/obj/item/door_seal = 10,
	list(
		/obj/item/language_manual/roundstart_species = 1
	) = 10,
	/obj/item/etherealballdeployer = 10,
	list(
		/obj/item/firing_pin/clown = 100,
		/obj/item/firing_pin/clown/ultra = 50,
		/obj/item/firing_pin/explorer = 25,
		/obj/item/firing_pin/paywall/luxury = 50,
		/obj/item/firing_pin/tag/blue = 5,
		/obj/item/firing_pin/tag/red = 5,
		/obj/item/firing_pin/test_range = 10,
		/obj/item/firing_pin/monkey = 5
	) = 10,
	list(
		/obj/item/implanter/mortis = 10,
		/obj/item/implanter/sad_trombone = 10,
		/obj/item/implanter/tracking = 1,
		/obj/item/implanter/tracking/gps = 1,
		/obj/item/implantpad = 5
	) = 10,
	/obj/item/lightreplacer = 25,
	/obj/item/locator = 5,
	/obj/item/mmi = 10,
	/obj/item/pinata = 20,
	/obj/item/pinpointer/material_sniffer = 5,
	list(
		/obj/item/pizzabox/margherita = 1,
		/obj/item/pizzabox/meat = 1,
		/obj/item/pizzabox/mushroom = 1,
		/obj/item/pizzabox/pineapple = 1,
		/obj/item/pizzabox/vegetable = 1,
		/obj/item/pizzabox/random = 3 //Mothic.
	) = 20,
	list(
		/obj/item/quickdeploy/barricade = 50,
		/obj/item/quickdeploy/barricade/plasteel = 10,
		/obj/item/storage/barricade = 5
	) = 20,
	list(
		/obj/item/restraints/legcuffs/beartrap = 10,
		/obj/item/restraints/legcuffs/beartrap/prearmed = 1
	) = 20,
	list(
		/obj/item/storage/medkit = 300,
		/obj/item/storage/medkit/regular = 200,
		/obj/item/storage/medkit/advanced = 25,
		/obj/item/storage/medkit/ancient = 5,
		/obj/item/storage/medkit/brute = 25,
		/obj/item/storage/medkit/coroner = 25,
		/obj/item/storage/medkit/emergency = 300,
		/obj/item/storage/medkit/fire = 25,
		/obj/item/storage/medkit/o2 = 25,
		/obj/item/storage/medkit/surgery = 5,
		/obj/item/storage/medkit/toxin = 25
	) = 50,
	/obj/item/crucifix = 5,
	list(
		/obj/item/hairbrush/switchblade = 5,
		/obj/item/hairbrush/tactical = 1
	) = 5,
	/obj/item/geneshears = 5,
	/obj/item/sign/flag/usa = 5,
	/obj/item/spess_knife = 5,
	/obj/item/borg_restart_board = 5,
	/obj/item/switchblade = 1,
	/obj/item/throwing_star = 5,
	/obj/item/grenade/primer/stingbang = 1,
	list(
		/obj/item/tank/internals/emergency_oxygen/engi/clown = 1,
		/obj/item/tank/internals/emergency_oxygen/engi/clown/n2o = 1,
		/obj/item/tank/internals/emergency_oxygen/engi/clown/bz = 1,
		/obj/item/tank/internals/emergency_oxygen/engi/clown/helium = 1
	) = 5,
	list(
		/obj/item/stack/sheet/mineral/adamantine = 1,
		/obj/item/stack/sheet/mineral/runite = 1,
		/obj/item/stack/sheet/mineral/mythril = 5,
		/obj/item/stack/sheet/mineral/abductor = 1,
		/obj/item/stack/sheet/runed_metal/five = 5,
		/obj/item/stack/sheet/hauntium/five = 25,
		/obj/item/stack/sheet/cobolterium/three = 50,
		/obj/item/stack/sheet/copporcitite/three = 50,
		/obj/item/stack/sheet/tinumium/three = 50,
		/obj/item/stack/sheet/brussite/three = 50,
	) = 20,
	/obj/item/reagent_containers/cup/soda_cans/shamblers/eldritch = 1,
	list(
		/obj/item/reagent_containers/spray/mister/pepperspray = 1,
		/obj/item/reagent_containers/spray/pepper = 10,
		/obj/item/reagent_containers/spray/pepper/empty = 100,
		/obj/item/reagent_containers/spray/medical = 50,
		/obj/item/reagent_containers/spray = 100,
	) = 50,
	/obj/item/implanter/toaster = 10,
	/obj/item/plunger/reinforced = 5,
	/obj/item/upgradescroll = 1,
	list(
		/obj/item/stake = 100,
		/obj/item/stake/hardened = 50,
		/obj/item/stake/hardened/silver = 25
	) = 10,
	/obj/item/lazarus_injector = 5,
	/obj/item/tailclub = 5,
	/obj/item/bikehorn/airhorn = 5,
	/obj/item/toy/snappop/phoenix = 5,
	/obj/item/melee/skateboard/pro = 5,
	list(
		/obj/item/book/granter/crafting_recipe/dusting/pipegun_prime = 1,
		/obj/item/book/granter/crafting_recipe/dusting/laser_musket_prime = 1
	) = 10,
	/obj/item/skillchip/intj = 5,

))
