no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Accessibility" = 0
"Administration" = 0
"Atomic" = 0
"Balance" = 0
"Code Improvement" = 0
"Documentation" = 0
"Feature" = 0
"Good First PR" = 0
"Feedback" = 0
"Fix" = 0
"Grammar and Formatting" = 0
"Hard Deletes" = 0
"Logging" = 0
"Performance" = 0
"Priority: CRITICAL" = 0
"Priority: High" = 0
"Quality of Life" = 0
"Refactor" = 0
"Sound" = 0
"Sprites" = 0
"Unit Tests" = 0
"Wallening Revert Recovery" = 0
