AIRALARM_TLV_TEMP_WARN_MIN (BODYTEMP_COLD_WARNING_1 + 7)
AIRALARM_TLV_TEMP_WARN_MAX (BODYTEMP_HEAT_WARNING_1 - 27)
FIREBOT_TLV_TEMP_WARN_MIN (AIRALARM_TLV_TEMP_WARN_MIN + 13)
FIREBOT_TLV_TEMP_WARN_MAX (AIRALARM_TLV_TEMP_WARN_MAX - 13)
