#define LOADOUT_BLACKLISTED_CLOTHING_TRAITS (LAVAPROTECT | STOPSPRESSUREDAMAGE | BLOCK_GAS_SMOKE_EFFECT | THICKMATERIAL | VOICEBOX_TOGGLABLE | DANGEROUS_OBJECT)

#define LOADOUT_BLACKLISTED_CLOTHING_RESISTANCES (LAVA_PROOF | FIRE_PROOF | UNACIDABLE | ACID_PROOF | INDESTRUCTIBLE | FREEZE_PROOF | SHUTTLE_CRUSH_PROOF)

#define LOADOUT_BLACKLISTED_ITEM_FLAGS (DROPDEL | NEEDS_PERMIT | ABSTRACT | HAND_ITEM)