GLOBAL_LIST_INIT(backpacklist, list(
	DBACKPACK,
	DDUFFELBAG,
	DSATCHEL,
	DMESSENGER,
	GBACKPACK,
	GDUFFELBAG,
	GSATCHEL,
	GMESSENGER,
	LSATCHEL,
	FBACKPACK, // BUBBER EDIT BEGIN
	FSATCHEL,
	FMESSENGER, // BUBBER EDIT END
))
