#define BSA_SYSTEM_READY "SYSTEM READY"
#define BSA_SYSTEM_PREFIRE "! SYSTEM PREFIRING !"
#define BSA_SYSTEM_FIRING "SYSTEM FIRING"
#define BSA_SYSTEM_RELOADING "SYSTEM RELOADING"
#define BSA_SYSTEM_LOW_POWER "SYSTEM POWER LOW"
#define BSA_SYSTEM_CHARGE_CAPACITORS "SYSTEM CHARGING CAPACITORS"

#define BSA_RELOAD_TIME 20 SECONDS
#define BSA_FIRE_POWER_THRESHOLD 1000000 // 1 MW
