/obj/item/survivalcapsule/plap
	name = "PLAP capsule"
	desc = "A bluespace capsule colored in syndie red and black. It has the letters PLAP written on it."
	template_id = "shelter_plap"
	icon_state = "scapsule"

/obj/item/paper/crumpled/plap
	name = "Guide to your PLAP (Portable Listening Advanced Post)"
	default_raw_text = {"<h1><table bgcolor="darkred" width="100%"><th><font color="#ffffff" size=4 face="OCR A Std, monospace"><div align="center">♦♦♦♦♦♦♦♦◹§◺♦♦♦♦♦♦♦♦</font></div></th></table></h1><hr /><font face="Veranda" size=3>Welcome to your very own "Portable" Listening Post! Now that you've unboxed the kit, lets get started on how everything works!<br><br>Included in this kit are:<br>* State of the art protective windows, from the dirty outside world!<br>* A computer bay fit to make the most hackerman of boys cry!<br>* A fax machine painted in sleek Syndicate Red.<br>* A filing cabinet! It's not special. Just a filing cabinet.<br><br>Listen to your foes! Stink up their comms! Find a cute girl to stalk! All is possible with the "Portable" Listening Post!<br><hr />The fax machine included in the PLP is set up to the Sothran network. It is not visible on any fax machines aboard the station, while still able to send to them. Use this to your advantage.</font><hr /><center><font size=3>❘❙❚❘❙❚|<span style="color:black;font-family:'Sitka Small Semibold';">There is glory in silence.</span>|❚❙❘❚❙❘</center><hr><div align="center"><font size=1>Warning. Portable Listening Post can not be moved once placed. Relies on power of the surrounding area. Comms agent not included. Basic knowledge of running communications arrays required. Do not ingest small parts that fall off computer keyboards.</div></font><hr><h1><table bgcolor="darkred" width="100%"><th><font color="#ffffff" size=4 face="OCR A Std, monospace"><div align="center">♦♦♦♦♦♦♦♦◹§◺♦♦♦♦♦♦♦♦</font></div></th></table></h1>"}
