//Reminders-
// If you add something to this list, please group it by type and sort it alphabetically instead of just jamming it in like an animal
// cost = 700- Minimum cost, or infinite points are possible.

/datum/supply_pack/science/T3_parts
	name = "Super Parts Crate"
	access = ACCESS_RESEARCH
	crate_type = /obj/structure/closet/crate/secure/science
	desc = "Want to upgrade the station, but don't have the materials for it? With this crate, you will be able to apply some much needed upgrades to much of the station's machinery! Contains 15 Super Matter Bins, Pico Manipulators, Super Capacitors, Phasic Scanning modules, Ultra High Power Lasers and 5 hyper capacity power cells."
	cost = 3500
	contains = list(/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/matter_bin/super,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/manipulator/pico,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/capacitor/super,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/scanning_module/phasic,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/micro_laser/ultra,
					/obj/item/stock_parts/cell/hyper,
					/obj/item/stock_parts/cell/hyper,
					/obj/item/stock_parts/cell/hyper,
					/obj/item/stock_parts/cell/hyper,
					/obj/item/stock_parts/cell/hyper)

// /datum/supply_pack/science/T4_parts // bit OP innit?
// 	name = "Bluespace Parts Crate"
// 	access = ACCESS_RESEARCH
// 	desc = "Want to upgrade the station, but don't have the materials for it? With this crate, you will be able to apply some much needed upgrades to much of the station's machinery! Contains 15 Bluespace Matter Bins, Femto Manipulators, Quadratic Capacitors, Triphasic Scanning modules, Quad Ultra Micro Lasers and 5 Bluespace power cells."
// 	cost = 5000
// 	contains = list(/obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/matter_bin/bluespace,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/manipulator/femto,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/scanning_module/triphasic,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/micro_laser/quadultra,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/capacitor/quadratic,
					// /obj/item/stock_parts/cell/bluespace,
					// /obj/item/stock_parts/cell/bluespace,
					// /obj/item/stock_parts/cell/bluespace,
					// /obj/item/stock_parts/cell/bluespace,
					// /obj/item/stock_parts/cell/bluespace)
				
// /datum/supply_pack/science/Bluespace_RPED
// 	name = "Bluespace RPED crate"
// 	desc = "Need to rebuild the ORM but science got annihilated after a bomb test? Buy this for the most advanced parts GT can give you." //GS13 - NT to GT
// 	cost = 4500
// 	contains = list(/obj/item/storage/part_replacer/cargo)
// 	crate_name = "\improper RPED crate"