// Generated by AI

/obj/structure/prop/general
	name = "A prop"
	desc = "Lazy me!"
	icon = 'modular_zvents/icons/structures/props/tgmc/urban/deco.dmi'

// Subtypes based on icon_states from the image
/obj/structure/prop/general/sidecabinet
	name = "Side Cabinet"
	desc = "A small cabinet for storage."
	icon_state = "sidecabinet"

/obj/structure/prop/general/slotmachine
	name = "Slot Machine"
	desc = "A gambling slot machine."
	icon_state = "slotmachine"

/obj/structure/prop/general/bigroller_up
	name = "Big Roller Up"
	desc = "A large rolling door in the up position."
	icon_state = "bigroller_up"

/obj/structure/prop/general/bigroller_down
	name = "Big Roller Down"
	desc = "A large rolling door in the down position."
	icon_state = "bigroller_down"

/obj/structure/prop/general/bigroller_up2
	name = "Big Roller Up 2"
	desc = "A second variant of a rolled-up door."
	icon_state = "bigroller_up2"

/obj/structure/prop/general/bigroller_down2
	name = "Big Roller Down 2"
	desc = "A second variant of a rolled-down door."
	icon_state = "bigroller_down2"

/obj/structure/prop/general/bigroller_up3
	name = "Big Roller Up 3"
	desc = "A third variant of a rolled-up door."
	icon_state = "bigroller_up3"

/obj/structure/prop/general/bigroller_down3
	name = "Big Roller Down 3"
	desc = "A third variant of a rolled-down door."
	icon_state = "bigroller_down3"

/obj/structure/prop/general/roadbarrier
	name = "Road Barrier"
	desc = "A barrier to block roads."
	icon_state = "roadbarrier"

/obj/structure/prop/general/roadbarrier2
	name = "Road Barrier 2"
	desc = "Another type of road barrier."
	icon_state = "roadbarrier2"

/obj/structure/prop/general/hospitalcurtain
	name = "Hospital Curtain"
	desc = "A curtain used in hospitals."
	icon_state = "hospitalcurtain"

/obj/structure/prop/general/roadbarrierjoined
	name = "Joined Road Barrier"
	desc = "A connected road barrier."
	icon_state = "roadbarrierjoined"

/obj/structure/prop/general/roadbarrierwood
	name = "Wooden Road Barrier"
	desc = "A wooden road barrier."
	icon_state = "roadbarrierwood"

/obj/structure/prop/general/roadbarrierpolice
	name = "Police Road Barrier"
	desc = "A police-issued road barrier."
	icon_state = "roadbarrierpolice"

/obj/structure/prop/general/roadbarrier3
	name = "Road Barrier 3"
	desc = "A third road barrier design."
	icon_state = "roadbarrier3"

/obj/structure/prop/general/roadbarrierjoined3
	name = "Joined Road Barrier 3"
	desc = "A third variant of a connected barrier."
	icon_state = "roadbarrierjoined3"

/obj/structure/prop/general/comfychair_zenithred
	name = "Zenith Red Comfy Chair"
	desc = "A red comfy chair from Zenith."
	icon_state = "comfychair_zenithred"

/obj/structure/prop/general/comfychair_zenithblue
	name = "Zenith Blue Comfy Chair"
	desc = "A blue comfy chair from Zenith."
	icon_state = "comfychair_zenithblue"

/obj/structure/prop/general/comfychair_zenithbrown
	name = "Zenith Brown Comfy Chair"
	desc = "A brown comfy chair from Zenith."
	icon_state = "comfychair_zenithbrown"

/obj/structure/prop/general/solidgrate
	name = "Solid Grate"
	desc = "A sturdy metal grate."
	icon_state = "solidgrate"

/obj/structure/prop/general/solidgrate1
	name = "Solid Grate 1"
	desc = "A first variant of a solid grate."
	icon_state = "solidgrate1"

/obj/structure/prop/general/solidgrate2
	name = "Solid Grate 2"
	desc = "A second solid grate design."
	icon_state = "solidgrate2"

/obj/structure/prop/general/solidgrate3
	name = "Solid Grate 3"
	desc = "A third solid grate variant."
	icon_state = "solidgrate3"

/obj/structure/prop/general/solidgrate4
	name = "Solid Grate 4"
	desc = "A fourth solid grate design."
	icon_state = "solidgrate4"

/obj/structure/prop/general/solidgrate5
	name = "Solid Grate 5"
	desc = "A fifth solid grate variant."
	icon_state = "solidgrate5"

/obj/structure/prop/general/prisonbed
	name = "Prison Bed"
	desc = "A basic bed for prisoners."
	icon_state = "prisonbed"

/obj/structure/prop/general/zbunkbed
	name = "Zenith Bunk Bed"
	desc = "A bunk bed from Zenith."
	icon_state = "zbunkbed"

/obj/structure/prop/general/zbunkbed2
	name = "Zenith Bunk Bed 2"
	desc = "A second Zenith bunk bed design."
	icon_state = "zbunkbed2"

/obj/structure/prop/general/zbunkbed3
	name = "Zenith Bunk Bed 3"
	desc = "A third Zenith bunk bed variant."
	icon_state = "zbunkbed3"

/obj/structure/prop/general/zbunkbed4
	name = "Zenith Bunk Bed 4"
	desc = "A fourth Zenith bunk bed design."
	icon_state = "zbunkbed4"

/obj/structure/prop/general/zhalfgrate1
	name = "Z Half Grate 1"
	desc = "A half grate from Zenith."
	icon_state = "zhalfgrate1"

/obj/structure/prop/general/foodcart1
	name = "Food Cart 1"
	desc = "A mobile food cart."
	icon_state = "foodcart1"

/obj/structure/prop/general/foodcart2
	name = "Food Cart 2"
	desc = "A second food cart design."
	icon_state = "foodcart2"

/obj/structure/prop/general/foodcart1_open
	name = "Food Cart 1 Open"
	desc = "An open mobile food cart."
	icon_state = "foodcart1_open"

/obj/structure/prop/general/foodcart2_open
	name = "Food Cart 2 Open"
	desc = "An open second food cart."
	icon_state = "foodcart2_open"

/obj/structure/prop/general/trashbag
	name = "Trash Bag"
	desc = "A bag full of trash."
	icon_state = "trashbag"

/obj/structure/prop/general/atm
	name = "ATM"
	desc = "An automated teller machine."
	icon_state = "atm"

/obj/structure/prop/general/atm_off
	name = "ATM Off"
	desc = "An inactive automated teller machine."
	icon_state = "atm_off"

/obj/structure/prop/general/atmtop
	name = "ATM Top"
	desc = "The top part of an ATM."
	icon_state = "atmtop"

/obj/structure/prop/general/weldtank
	name = "Weld Tank"
	desc = "A tank for welding gas."
	icon_state = "weldtank"

/obj/structure/prop/general/redmeter
	name = "Red Meter"
	desc = "A red utility meter."
	icon_state = "redmeter"

/obj/structure/prop/general/coffee
	name = "Coffee Machine"
	desc = "A machine for brewing coffee."
	icon_state = "coffee"

/obj/structure/prop/general/coffee_cup
	name = "Coffee Cup"
	desc = "A single coffee cup."
	icon_state = "coffee_cup"

/obj/structure/prop/general/coffeecuppaijoe
	name = "Coffee Cuppa Joe"
	desc = "A cup of Joe coffee."
	icon_state = "coffeecuppaijoe"

/obj/structure/prop/general/coffeecuppaijoek
	name = "Coffee Cuppa Joe K"
	desc = "A variant of Cuppa Joe coffee."
	icon_state = "coffeecuppaijoek"

/obj/structure/prop/general/coffeecuppaijoestac
	name = "Coffee Cuppa Joe Stac"
	desc = "A stacked Cuppa Joe coffee."
	icon_state = "coffeecuppaijoestac"

/obj/structure/prop/general/coffeecuppaijoenoli
	name = "Coffee Cuppa Joe Noli"
	desc = "A unique Cuppa Joe variant."
	icon_state = "coffeecuppaijoenoli"

/obj/structure/prop/general/coffeecuppaijoestac_k2
	name = "Coffee Cuppa Joe Stac K2"
	desc = "A stacked K2 variant of Cuppa Joe."
	icon_state = "coffeecuppaijoestac_k2"

/obj/structure/prop/general/coffeecuppaijoe_k2nolid
	name = "Coffee Cuppa Joe K2 Nolid"
	desc = "A K2 Nolid variant of Cuppa Joe."
	icon_state = "coffeecuppaijoe_k2nolid"

/obj/structure/prop/general/hospital
	name = "Hospital Sign"
	desc = "A sign indicating a hospital."
	icon_state = "hospital"

/obj/structure/prop/general/0-1
	name = "Marker 0-1"
	desc = "A small distance marker."
	icon_state = "0-1"

/obj/structure/prop/general/1-2
	name = "Marker 1-2"
	desc = "Another distance marker."
	icon_state = "1-2"

/obj/structure/prop/general/1-4
	name = "Marker 1-4"
	desc = "A third distance marker."
	icon_state = "1-4"

/obj/structure/prop/general/1-2-4
	name = "Marker 1-2-4"
	desc = "A combined distance marker."
	icon_state = "1-2-4"

/obj/structure/prop/general/1-2-4-8
	name = "Marker 1-2-4-8"
	desc = "A more detailed distance marker."
	icon_state = "1-2-4-8"

/obj/structure/prop/general/zfloorpanel
	name = "Z Floor Panel"
	desc = "A floor panel from Zenith."
	icon_state = "zfloorpanel"

/obj/structure/prop/general/platform
	name = "Platform"
	desc = "A small elevated platform."
	icon_state = "platform"

/obj/structure/prop/general/zenithplatform3
	name = "Zenith Platform 3"
	desc = "A third Zenith platform design."
	icon_state = "zenithplatform3"

/obj/structure/prop/general/highvoltagegrille
	name = "High Voltage Grille"
	desc = "A high-voltage protective grille."
	icon_state = "highvoltagegrille"

/obj/structure/prop/general/highvoltagegrille_off
	name = "High Voltage Grille Off"
	desc = "An inactive high-voltage grille."
	icon_state = "highvoltagegrille_off"

/obj/structure/prop/general/highvoltagegrille_broken
	name = "High Voltage Grille Broken"
	desc = "A broken high-voltage grille."
	icon_state = "highvoltagegrille_broken"

/obj/structure/prop/general/smallwallvent1
	name = "Small Wall Vent 1"
	desc = "A small wall-mounted vent."
	icon_state = "smallwallvent1"

/obj/structure/prop/general/smallwallvent2
	name = "Small Wall Vent 2"
	desc = "A second small wall vent."
	icon_state = "smallwallvent2"

/obj/structure/prop/general/smallwallvent3
	name = "Small Wall Vent 3"
	desc = "A third small wall vent."
	icon_state = "smallwallvent3"

/obj/structure/prop/general/biggreenmeter1
	name = "Big Green Meter 1"
	desc = "A large green utility meter."
	icon_state = "biggreenmeter1"

/obj/structure/prop/general/zcomputermachine
	name = "Z Computer Machine"
	desc = "A Zenith computer system."
	icon_state = "zcomputermachine"

/obj/structure/prop/general/zcomputermachine_off
	name = "Z Computer Machine Off"
	desc = "An inactive Zenith computer."
	icon_state = "zcomputermachine_off"

/obj/structure/prop/general/wymanhole
	name = "Wyman Hole"
	desc = "A manhole cover."
	icon_state = "wymanhole"

/obj/structure/prop/general/wymanhole_open
	name = "Wyman Hole Open"
	desc = "An open manhole cover."
	icon_state = "wymanhole_open"

/obj/structure/prop/general/wymanhole_open2
	name = "Wyman Hole Open 2"
	desc = "A second open manhole design."
	icon_state = "wymanhole_open2"

/obj/structure/prop/general/wymanhole_open3
	name = "Wyman Hole Open 3"
	desc = "A third open manhole variant."
	icon_state = "wymanhole_open3"

/obj/structure/prop/general/maintenancehatch
	name = "Maintenance Hatch"
	desc = "A hatch for maintenance access."
	icon_state = "maintenancehatch"

/obj/structure/prop/general/maintenancehatch_alt
	name = "Maintenance Hatch Alt"
	desc = "An alternative maintenance hatch."
	icon_state = "maintenancehatch_alt"

/obj/structure/prop/general/maintenancehatch_alt_open
	name = "Maintenance Hatch Alt Open"
	desc = "An open alternative maintenance hatch."
	icon_state = "maintenancehatch_alt_open"

/obj/structure/prop/general/roadbarrier4
	name = "Road Barrier 4"
	desc = "A fourth road barrier design."
	icon_state = "roadbarrier4"

/obj/structure/prop/general/roadbarrier5
	name = "Road Barrier 5"
	desc = "A fifth road barrier variant."
	icon_state = "roadbarrier5"

/obj/structure/prop/general/roadbarrier6
	name = "Road Barrier 6"
	desc = "A sixth road barrier design."
	icon_state = "roadbarrier6"

/obj/structure/prop/general/detonator
	name = "Detonator"
	desc = "A device for triggering explosions."
	icon_state = "detonator"

/obj/structure/prop/general/firehydrant
	name = "Fire Hydrant"
	desc = "A hydrant for firefighting."
	icon_state = "firehydrant"

/obj/structure/prop/general/panelpower
	name = "Power Panel"
	desc = "A control panel for power."
	icon_state = "panelpower"

/obj/structure/prop/general/paneloff
	name = "Power Panel Off"
	desc = "An inactive power control panel."
	icon_state = "paneloff"

/obj/structure/prop/general/panelon
	name = "Power Panel On"
	desc = "An active power control panel."
	icon_state = "panelon"

/obj/structure/prop/general/floorspotlight_off
	name = "Floor Spotlight Off"
	desc = "An inactive floor spotlight."
	icon_state = "floorspotlight_off"

/obj/structure/prop/general/floorspotlight_on
	name = "Floor Spotlight On"
	desc = "An active floor spotlight."
	icon_state = "floorspotlight_on"

/obj/structure/prop/general/centerroadbarrier
	name = "Center Road Barrier"
	desc = "A central road barrier."
	icon_state = "centerroadbarrier"

/obj/structure/prop/general/centerroadbarrier2
	name = "Center Road Barrier 2"
	desc = "A second central road barrier."
	icon_state = "centerroadbarrier2"

/obj/structure/prop/general/centerroadbarrier3
	name = "Center Road Barrier 3"
	desc = "A third central road barrier."
	icon_state = "centerroadbarrier3"

/obj/structure/prop/general/frame
	name = "Frame"
	desc = "A structural frame."
	icon_state = "frame"

/obj/structure/prop/general/security
	name = "Security Console"
	desc = "A console for security monitoring."
	icon_state = "security"

/obj/structure/prop/general/evac
	name = "Evacuation Sign"
	desc = "A sign for evacuation routes."
	icon_state = "evac"

/obj/structure/prop/general/redalert
	name = "Red Alert"
	desc = "A red alert indicator."
	icon_state = "redalert"

/obj/structure/prop/general/redalertblank
	name = "Red Alert Blank"
	desc = "A blank red alert panel."
	icon_state = "redalertblank"

/obj/structure/prop/general/telescreen
	name = "Telescreen"
	desc = "A screen for announcements."
	icon_state = "telescreen"

/obj/structure/prop/general/multimonitor_small_off
	name = "Small Monitor Off"
	desc = "A small inactive monitor."
	icon_state = "multimonitor_small_off"

/obj/structure/prop/general/multimonitor_small_on
	name = "Small Monitor On"
	desc = "A small active monitor."
	icon_state = "multimonitor_small_on"

/obj/structure/prop/general/multimonitorbig_off
	name = "Big Monitor Off"
	desc = "A large inactive monitor."
	icon_state = "multimonitorbig_off"

/obj/structure/prop/general/multimonitorbig_on
	name = "Big Monitor On"
	desc = "A large active monitor."
	icon_state = "multimonitorbig_on"

/obj/structure/prop/general/multimonitormedium_off
	name = "Medium Monitor Off"
	desc = "A medium inactive monitor."
	icon_state = "multimonitormedium_off"

/obj/structure/prop/general/multimonitormedium_on
	name = "Medium Monitor On"
	desc = "A medium active monitor."
	icon_state = "multimonitormedium_on"

/obj/structure/prop/general/bluemultimonitors
	name = "Blue Monitors"
	desc = "A set of blue monitors."
	icon_state = "bluemultimonitors"

/obj/structure/prop/general/bluemultimonitors_off
	name = "Blue Monitors Off"
	desc = "A set of inactive blue monitors."
	icon_state = "bluemultimonitors_off"

/obj/structure/prop/general/bluemultimonitors_g_off
	name = "Blue Monitors G Off"
	desc = "A set of inactive green-blue monitors."
	icon_state = "bluemultimonitors_g_off"

/obj/structure/prop/general/bluemultimonitorbi
	name = "Blue Multi Monitor Bi"
	desc = "A bicolor blue monitor setup."
	icon_state = "bluemultimonitorbi"

/obj/structure/prop/general/edium_off
	name = "Edium Off"
	desc = "An inactive edium device."
	icon_state = "edium_off"

/obj/structure/prop/general/edium_on
	name = "Edium On"
	desc = "An active edium device."
	icon_state = "edium_on"

/obj/structure/prop/general/wallegg_on
	name = "Wall Egg On"
	desc = "An active wall-mounted egg device."
	icon_state = "wallegg_on"

/obj/structure/prop/general/wallegg_off
	name = "Wall Egg Off"
	desc = "An inactive wall-mounted egg device."
	icon_state = "wallegg_off"

/obj/structure/prop/general/trashgreen
	name = "Green Trash"
	desc = "A green trash container."
	icon_state = "trashgreen"

/obj/structure/prop/general/trashblue
	name = "Blue Trash"
desc = "A blue trash container."
	icon_state = "trashblue"

/obj/structure/prop/general/shockbig
	name = "Shock Big"
desc = "A large shock device."
	icon_state = "shockbig"

/obj/structure/prop/general/shocktiny
	name = "Shock Tiny"
desc = "A small shock device."
	icon_state = "shocktiny"

/obj/structure/prop/general/barrel_wy
	name = "Barrel WY"
desc = "A barrel from WY corporation."
	icon_state = "barrel_wy"

/obj/structure/prop/general/barrel_tan
	name = "Barrel Tan"
desc = "A tan-colored barrel."
	icon_state = "barrel_tan"

/obj/structure/prop/general/barrel_purewhite
	name = "Barrel Pure White"
desc = "A pure white barrel."
	icon_state = "barrel_purewhite"

/obj/structure/prop/general/red_pipe_s
	name = "Red Pipe S"
desc = "A small red pipe."
	icon_state = "red_pipe_s"

/obj/structure/prop/general/red_pipe_c
	name = "Red Pipe C"
desc = "A curved red pipe."
	icon_state = "red_pipe_c"

/obj/structure/prop/general/red_pipe_j1
	name = "Red Pipe J1"
desc = "A jointed red pipe variant."
	icon_state = "red_pipe_j1"

/obj/structure/prop/general/red_pipe_y
	name = "Red Pipe Y"
desc = "A Y-shaped red pipe."
	icon_state = "red_pipe_y"

/obj/structure/prop/general/red_pipe_b
	name = "Red Pipe B"
desc = "A basic red pipe."
	icon_state = "red_pipe_b"
