#define RAPTOR_TEMP_OFFSET -30
#define RAPTOR_HEATMOD 1.1
#define RAPTOR_COLDMOD 0.8

#define RAPTOR_HUNGERMOD 0.5

#define TESHARI_ALT_TEMP_OFFSET -50
#define TESHARI_ALT_HEATMOD 1.4
#define TESHARI_ALT_COLDMOD 0.2
