#define CHANGELING_ZOMBIE_TRAIT "changelingzombie"

#define CHANGELING_ZOMBIE_TOXINS_PER_SECOND_LIVING 0.5
#define CHANGELING_ZOMBIE_TOXINS_PER_SECOND_DEAD 3
#define CHANGELING_ZOMBIE_PASSIVE_HEALING 1 //Randomy chosen between brute, burn, oxy, and burn, if damaged.
#define CHANGELING_ZOMBIE_LIMB_REGEN_TIME 30 SECONDS