// NOTE TO FUTURE CODERS: If you increase this to a huge number, please restrict the overall **amount** of items players can take,
// if item count restrictions have been significantly increased. You will end up with massively bloated save sizes otherwise.
#define LOADOUT_MAX_PRESETS 12
#define LOADOUT_MAX_NAME_LENGTH 24

#define ALL_JOBS_SEC JOB_WARDEN, JOB_DETECTIVE, JOB_SECURITY_OFFICER, JOB_SECURITY_OFFICER_MEDICAL, JOB_SECURITY_OFFICER_ENGINEERING, JOB_SECURITY_OFFICER_SCIENCE, JOB_SECURITY_OFFICER_SUPPLY, JOB_SECURITY_OFFICER_SERVICE, JOB_HEAD_OF_SECURITY, JOB_CORRECTIONS_OFFICER, JOB_SECURITY_MEDIC
#define ALL_JOBS_DEPT_GUARDS JOB_CORRECTIONS_OFFICER, JOB_SECURITY_OFFICER_ENGINEERING, JOB_SECURITY_OFFICER_MEDICAL, JOB_SECURITY_OFFICER_SCIENCE, JOB_SECURITY_OFFICER_SUPPLY, JOB_SECURITY_OFFICER_SERVICE
#define ALL_JOBS_CENTRAL JOB_NT_REP, JOB_BLUESHIELD
#define ALL_JOBS_MEDICAL JOB_MEDICAL_DOCTOR, JOB_CHIEF_MEDICAL_OFFICER, JOB_CHEMIST, JOB_PARAMEDIC, JOB_SECURITY_OFFICER_MEDICAL, JOB_CORONER
#define ALL_JOBS_SCIENCE JOB_SCIENTIST, JOB_ROBOTICIST, JOB_GENETICIST, JOB_RESEARCH_DIRECTOR, JOB_CHEMIST, JOB_SECURITY_OFFICER_SCIENCE
#define ALL_JOBS_CARGO JOB_QUARTERMASTER, JOB_CARGO_TECHNICIAN, JOB_SECURITY_OFFICER_SUPPLY, JOB_SHAFT_MINER, JOB_BITRUNNER
#define ALL_JOBS_ENGINEERING JOB_CHIEF_ENGINEER, JOB_STATION_ENGINEER, JOB_ATMOSPHERIC_TECHNICIAN, JOB_SECURITY_OFFICER_ENGINEERING
