#define span_subtle(str) ("<span class='subtle'>" + str + "</span>")
#define span_subtlepda(str) ("<span class='subtlepda'>" + str + "</span>")
#define span_subtler(str) ("<span class='subtler'>" + str + "</span>")
#define span_velvet(str) ("<span class='velvet'>" + str + "</span>")
#define span_velvet_notice(str) ("<span class='velvet_notice'>" + str + "</span>")
#define vote_font(str) ("<span class='vote'>" + str + "</span>")
#define span_yellow_flashy(str) ("<span class='glossy'>" + str + "</span>")
