/obj/item/storage/bag/garment/warden/PopulateContents()
	new /obj/item/clothing/under/rank/security/warden(src)
	new /obj/item/clothing/under/rank/security/warden/skirt(src)
	new /obj/item/clothing/under/rank/security/warden/formal(src)
	new /obj/item/clothing/under/rank/security/warden/formal/skirt(src)
	new /obj/item/clothing/head/hats/warden/viro(src)
	new /obj/item/clothing/head/hats/warden/viro/alt(src)
	new /obj/item/clothing/head/hats/warden/viro/beret(src)
	new /obj/item/clothing/head/hats/warden/drill/viro(src)
	new /obj/item/clothing/head/soft/sec/warden(src)
	new /obj/item/clothing/suit/armor/vest/warden/alt(src)
	new /obj/item/clothing/suit/armor/vest/warden(src)
	new /obj/item/clothing/suit/armor/vest/warden/alt/winter(src)
	new /obj/item/clothing/gloves/kaza_ruk/sec(src)
	new /obj/item/clothing/glasses/hud/security/sunglasses(src)
	new /obj/item/clothing/mask/gas/sechailer(src)

/obj/item/storage/bag/garment/hos/PopulateContents()
	new	/obj/item/clothing/under/rank/security/head_of_security(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/alt(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/alt/skirt(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/parade(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/parade/female(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/formal(src)
	new	/obj/item/clothing/under/rank/security/head_of_security/formal/skirt(src)
	new	/obj/item/clothing/head/hats/hos/cap(src)
	new	/obj/item/clothing/head/hats/hos/cap/beret(src)
	new /obj/item/clothing/head/helmet/sec/hos(src)
	new /obj/item/clothing/head/soft/sec/hos(src)
	new /obj/item/clothing/head/hats/hos/cap/cowboy(src)
	new	/obj/item/clothing/suit/armor/hos(src)
	new	/obj/item/clothing/suit/armor/hos/trenchcoat(src)
	new	/obj/item/clothing/suit/armor/hos/trenchcoat/winter(src)
	new	/obj/item/clothing/suit/armor/hos/overcoat(src)
	new /obj/item/clothing/suit/armor/hos/vest(src)
	new	/obj/item/clothing/neck/cloak/hos(src)
	new	/obj/item/clothing/mask/gas/sechailer/swat(src)
	new	/obj/item/clothing/shoes/sneakers/brown(src)
