/obj/machinery/vending/clothing
	zubbers_product_categories = list(
		list(
			"name" = "Head",
			"icon" = "hat-cowboy",
			"products" = list(
				/obj/item/clothing/head/avipilot = 5,
				/obj/item/clothing/head/back_bow = 5,
				/obj/item/clothing/head/beret/badge = 5,
				/obj/item/clothing/head/beret/clown/rainbow = 5,
				/obj/item/clothing/head/colourable_flatcap = 5,
				/obj/item/clothing/head/costume/sombrero = 3,
				/obj/item/clothing/head/costume/ushanka/frosty = 5,
				/obj/item/clothing/head/cowboy/skyrat/cattleman = 5,
				/obj/item/clothing/head/cowboy/skyrat/cattleman/wide = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/cowl = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/cowl/sheriff = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/deputy = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/sheriff = 5,
				/obj/item/clothing/head/cowboy/skyrat/wide = 5,
				/obj/item/clothing/head/cowboy/skyrat/wide/feathered = 5,
				/obj/item/clothing/head/fedora/beige = 5,
				/obj/item/clothing/head/fedora/brown = 5,
				/obj/item/clothing/head/fedora/white = 5,
				/obj/item/clothing/head/fedora = 5,
				/obj/item/clothing/head/henchmen_hat = 5,
				/obj/item/clothing/head/hooded/standalone_hood = 5,
				/obj/item/clothing/head/large_bow = 5,
				/obj/item/clothing/head/small_bow = 5,
				/obj/item/clothing/head/soft/galfedcap = 5,
				/obj/item/clothing/head/sweet_bow = 5,
			),
		),

		list(
			"name" = "Accessories",
			"icon" = "glasses",
			"products" = list(
				/obj/item/clothing/accessory/badge/holo/jade = 5,
				/obj/item/clothing/accessory/medal/steele = 5,
				/obj/item/clothing/glasses/eyepatch/rosecolored = 5,
				/obj/item/clothing/glasses/gold_aviators = 5,
				/obj/item/clothing/glasses/hud/ar/projector = 5,
				/obj/item/clothing/glasses/hud/civilian = 5,
				/obj/item/clothing/glasses/regular/betterunshit = 5,
				/obj/item/clothing/glasses/rosecolored = 5,
				/obj/item/clothing/glasses/thin = 5,
				/obj/item/clothing/glasses/welding/steampunk_goggles = 5,
				/obj/item/clothing/gloves/bracer/wraps = 5,
				/obj/item/clothing/gloves/cat = 5,
				/obj/item/clothing/gloves/elofy = 5,
				/obj/item/clothing/gloves/fingerless/blutigen_wraps = 5,
				/obj/item/clothing/gloves/skyy = 5,
				/obj/item/clothing/mask/gas/nightlight = 5,
				/obj/item/clothing/mask/gas/nightlight/fir22 = 5,
				/obj/item/clothing/neck/cloak/colourable = 5,
				/obj/item/clothing/neck/cloak/colourable/boat = 5,
				/obj/item/clothing/neck/cloak/colourable/shroud = 5,
				/obj/item/clothing/neck/cloak/colourable/veil = 5,
				/obj/item/clothing/neck/cloak/fluffycloak = 5,
				/obj/item/clothing/neck/cloak/inferno = 5,
				/obj/item/clothing/neck/cross = 5,
				/obj/item/clothing/neck/face_scarf = 5,
				/obj/item/clothing/neck/fishpendant = 5,
				/obj/item/clothing/neck/long_cape = 5,
				/obj/item/clothing/neck/mantle/recolorable = 5,
				/obj/item/clothing/neck/ranger_poncho = 5,
				/obj/item/clothing/neck/robe_cape = 5,
				/obj/item/clothing/neck/scarf/pride = 5,
				/obj/item/clothing/neck/wide_cape = 5,
			),
		),

		list(
			"name" = "Under",
			"icon" = "shirt",
			"products" = list(
				/obj/item/clothing/under/caged_dress/skirt = 5,
				/obj/item/clothing/under/costume/skyrat/kilt/royal = 5,
				/obj/item/clothing/under/costume/skyrat/kimono/sigmar = 5,
				/obj/item/clothing/under/costume/skyrat/tac/irish = 5,
				/obj/item/clothing/under/custom/blutigen_undergarment = 5,
				/obj/item/clothing/under/custom/lannese = 5,
				/obj/item/clothing/under/custom/lannese/vambrace = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/long = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/medium = 5,
				/obj/item/clothing/under/misc/bluetracksuit = 5,
				/obj/item/clothing/under/misc/skyrat/mechanic = 5,
				/obj/item/clothing/under/pants/skyrat/jeans_ripped = 5,
				/obj/item/clothing/under/pants/skyrat/kilt = 5,
				/obj/item/clothing/under/pants/skyrat/yoga = 5,
				/obj/item/clothing/under/pants/skyy = 5,
				/obj/item/clothing/under/red_and_white_collared_outfit = 5,
				/obj/item/clothing/under/shorts/skyrat/shorts_ripped = 5,
				/obj/item/clothing/under/suit/fancy = 5,
				/obj/item/clothing/under/suit/skyrat/black_really_collared = 3,
				/obj/item/clothing/under/suit/skyrat/black_really_collared/skirt = 3,
				/obj/item/clothing/under/suit/skyrat/helltaker = 3,
				/obj/item/clothing/under/suit/skyrat/helltaker/skirt = 3,
				/obj/item/clothing/under/suit/skyrat/inferno = 3,
				/obj/item/clothing/under/suit/skyrat/inferno/skirt = 3,
				/obj/item/clothing/under/suit/skyrat/pencil = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/black_really = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/burgandy = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/charcoal = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/checkered = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/green = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/navy = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/tan = 3,
				/obj/item/clothing/under/suit/skyrat/recolorable = 5,
				/obj/item/clothing/under/suit/skyrat/recolorable/skirt = 5,
				/obj/item/clothing/under/sweater = 5,
				/obj/item/clothing/under/sweater/keyhole = 5,
				/obj/item/clothing/under/syndicate/tacticool/black = 5,
				/obj/item/clothing/under/tachawaiian = 5,
				/obj/item/clothing/under/tachawaiian/blue = 5,
				/obj/item/clothing/under/tachawaiian/green = 5,
				/obj/item/clothing/under/tachawaiian/purple = 5,
				/obj/item/clothing/under/tactichill = 5,
				/obj/item/clothing/under/texas = 5,
			),
		),

		list(
			"name" = "Suits & Skirts",
			"icon" = "vest",
			"products" = list(
				/obj/item/clothing/suit/apron/chef/colorable_apron = 5,
				/obj/item/clothing/suit/blutigen_kimono = 5,
				/obj/item/clothing/suit/crop_jacket = 5,
				/obj/item/clothing/suit/crop_jacket/long = 5,
				/obj/item/clothing/suit/crop_jacket/shortsleeve = 5,
				/obj/item/clothing/suit/crop_jacket/shortsleeve/long = 5,
				/obj/item/clothing/suit/crop_jacket/sleeveless = 5,
				/obj/item/clothing/suit/crop_jacket/sleeveless/long = 5,
				/obj/item/clothing/suit/croptop = 5,
				/obj/item/clothing/suit/duster = 5,
				/obj/item/clothing/suit/fallsparka = 5,
				/obj/item/clothing/suit/furcoat = 5,
				/obj/item/clothing/suit/heart_sweater = 5,
				/obj/item/clothing/suit/hooded/big_hoodie = 5,
				/obj/item/clothing/suit/hooded/sigmarcoat = 5,
				/obj/item/clothing/suit/hooded/twee_hoodie = 5,
				/obj/item/clothing/suit/hooded/wintercoat/colourable = 5,
				/obj/item/clothing/suit/jacket/cherno = 5,
				/obj/item/clothing/suit/jacket/delta = 5,
				/obj/item/clothing/suit/jacket/galfed = 5,
				/obj/item/clothing/suit/jacket/henchmen_coat = 5,
				/obj/item/clothing/suit/jacket/hydrogenrobes = 5,
				/obj/item/clothing/suit/jacket/skyy = 5,
				/obj/item/clothing/suit/jacket/tailcoat = 5,
				/obj/item/clothing/suit/misc/suit_harness = 5,
				/obj/item/clothing/suit/modernwintercoatthing = 5,
				/obj/item/clothing/suit/short_coat = 5,
				/obj/item/clothing/suit/toggle/jacket = 5,
				/obj/item/clothing/suit/toggle/jacket/cardigan = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/aqua = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/brown = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/gags = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/red = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/cti = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/mu = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/nrti = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/smw = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/trim = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/trim/alt = 5,
				/obj/item/clothing/suit/toggle/jacket/zubber/bomber = 5,
				/obj/item/clothing/suit/toggle/jacket/zubber/bomber/science/coroner = 5,
				/obj/item/clothing/suit/toggle/labcoat/skyrat/tenrai = 5,
				/obj/item/clothing/suit/toggle/lawyer/white = 5,
				/obj/item/clothing/suit/toggle/peacoat = 5,
				/obj/item/clothing/suit/toggle/trackjacket = 5,
				/obj/item/clothing/suit/urban = 5,
				/obj/item/clothing/suit/varsity = 5,
				/obj/item/clothing/suit/warm_coat = 5,
				/obj/item/clothing/suit/warm_sweater = 5,
				/obj/item/clothing/under/dress/miniskirt = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/black_skirt = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/jean = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/lone_skirt = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/turtleskirt_knit = 5,
				/obj/item/clothing/under/dress/skyrat/flower = 5,
				/obj/item/clothing/under/dress/skyrat/pentagram = 5,
				/obj/item/clothing/under/dress/skyrat/pinktutu = 5,
				/obj/item/clothing/under/dress/skyrat/short_dress = 5,
				/obj/item/clothing/under/dress/skyrat/strapless = 5,
				/obj/item/clothing/under/dress/bubber/midnight_gown = 5,
			),
		),

		list(
			"name" = "Shoes",
			"icon" = "socks",
			"products" = list(
				/obj/item/clothing/shoes/colorable_laceups = 5,
				/obj/item/clothing/shoes/colorable_sandals = 5,
				/obj/item/clothing/shoes/fancy_heels/drag = 5,
				/obj/item/clothing/shoes/horseshoe = 5,
				/obj/item/clothing/shoes/jackboots/diesel_f = 5,
				/obj/item/clothing/shoes/jackboots/diesel_m = 5,
				/obj/item/clothing/shoes/jackboots/elofy = 5,
				/obj/item/clothing/shoes/jackboots/knee = 5,
				/obj/item/clothing/shoes/jackboots/netra = 5,
				/obj/item/clothing/shoes/jackboots/recolorable = 5,
				/obj/item/clothing/shoes/jungleboots = 5,
				/obj/item/clothing/shoes/sports = 5,
				/obj/item/clothing/shoes/wraps/cloth = 5,
				/obj/item/clothing/shoes/wraps/colourable = 5,
			),
		),

		//Only put clothing in Special thats either Families or exteremly out-of-place
		list(
			"name" = "Special",
			"icon" = "star",
			"products" = list(
				/obj/item/clothing/head/drake_skull = 5,
				/obj/item/clothing/mask/animal/wolf = 5,
				/obj/item/clothing/mask/gas/respirator = 5,
				/obj/item/clothing/mask/surgical/greyscale = 5,
				/obj/item/clothing/under/costume/deckers/alt = 5,
				/obj/item/clothing/under/costume/skyrat/bathrobe = 5,
				/obj/item/clothing/under/rank/civilian/bubber/camo = 5,
				/obj/item/riding_saddle/leather = 5,
				/obj/item/storage/backpack/saddlebags = 5,
				/obj/item/umbrella = 20,
				/obj/item/umbrella/parasol = 20,
			)
		)
	)

	zubbers_premium = list( //being here means you're even more artificially rare, congratulations
		/obj/item/clothing/head/razurathhat = 2,
		/obj/item/clothing/head/soft/yankee = 3,
		/obj/item/clothing/shoes/jackboots/noble = 2,
		/obj/item/clothing/shoes/jackboots/timbs = 2,
		/obj/item/clothing/suit/blackfurrich = 1,
		/obj/item/clothing/suit/brownbattlecoat = 1,
		/obj/item/clothing/suit/frenchtrench = 1,
		/obj/item/clothing/suit/hooded/colorblockhoodie = 2,
		/obj/item/clothing/suit/razurathcoat = 2,
	)

	zubbers_contraband = list(
		/obj/item/clothing/suit/jacket/ryddid = 3,
		/obj/item/clothing/neck/cloak/grunnyyy = 3,
		/obj/item/clothing/gloves/ring/hypno/coffeepot = 2,
		/obj/item/clothing/mask/hheart = 2,
		/obj/item/clothing/suit/toggle/digicoat/glitched = 2,
		/obj/item/clothing/neck/scarf/shadekin = 2, //Made of a sentient so probably illegal
	)
