directory = "_maps/map_files/biodome/modules/"

[rooms.cage_1]
modules = ["cage_1_axolotl.dmm", "cage_1_creature.dmm", "cage_1_fox.dmm", "cage_1_goat.dmm"]

[rooms.cage_2]
modules = ["cage_2_ghost.dmm", "cage_2_gondola.dmm", "cage_2_vibebot.dmm"]

[rooms.cage_3]
modules = ["cage_3_rabbit.dmm", "cage_3_gnome.dmm", "cage_3_lizard.dmm", "cage_3_rat.dmm"]

[rooms.cage_4]
modules = ["cage_4_cockroach.dmm", "cage_4_spider.dmm", "cage_4_slime.dmm"]
