directory = "_maps/map_files/FlotillaStation/modular_parts/"

# Section in the center of Security
[rooms.shooting_range]
modules = ["shooting_range_1.dmm", "shooting_range_2.dmm", "shooting_range_3.dmm", "shooting_range_4.dmm", "shooting_range_5.dmm"]
