/datum/weather/rad_storm/New(...)
	LAZYOR(protected_areas,/area/station/terminal)
	LAZYOR(protected_areas,/area/lavaland/underground)
	LAZYOR(protected_areas,/area/moonstation/underground)
	LAZYOR(protected_areas,/area/station/cargo/miningelevators)
	LAZYOR(protected_areas,/area/station/cargo/miningfoundry/event_protected)
	. = ..()