#define MAX_BELLIES 10
#define MAX_PREY 3
#define MATRYOSHKA_ALLOWED FALSE
#define VORE_DELAY 30 SECONDS
#define FRIES_SENSORS TRUE

#define DIGEST_MODE_NONE "None"
#define DIGEST_MODE_DIGEST "Digest"
