#define MAX_BELLIES 10
#define MAX_PREY 3
#define VORE_DELAY 1 SECONDS // TODO: Change to 30 SECONDS
#define MATRYOSHKA_ALLOWED FALSE
#define FRIES_SENSORS TRUE
#define REQUIRES_PLAYER FALSE // TODO: Change this
#define HUMAN_ONLY FALSE // TODO: Change this

#define DIGEST_MODE_NONE "None"
#define DIGEST_MODE_DIGEST "Digest"
