#undef MAX_BELLIES
#undef MAX_PREY
#undef VORE_DELAY
#undef RESIST_ESCAPE_DELAY
#undef MATRYOSHKA_BANNED
#undef DISABLES_SENSORS
#undef REQUIRES_PLAYER
#undef BELLY_BACKUP_COUNT
#undef MAX_BELLY_LAYOUTS

#undef TRAIT_SOURCE_VORE

#undef DIGEST_MODE_NONE
#undef DIGEST_MODE_DIGEST

#undef MAX_BURN_DAMAGE
#undef MAX_BRUTE_DAMAGE

#undef PREF_TRINARY_NEVER
#undef PREF_TRINARY_PROMPT
#undef PREF_TRINARY_ALWAYS

#undef CHANNEL_PREYLOOP
#undef COOLDOWN_PREYLOOP
