// The actual code to work these in
// Bubberstation custom borg sprites, to add new defines for icons and hat offsets go to code\_DEFINES\~~bubber_defines.dm

/* Centcom Cyborgs */

/obj/item/robot_model/centcom
	name = "Central Command"
	basic_modules = list(
		/obj/item/assembly/flash/cyborg,
		/obj/item/pen/cyborg,
		/obj/item/clipboard/cyborg,
		/obj/item/hand_labeler/cyborg,
		/obj/item/stamp/centcom,
		/obj/item/borg/paperplane_crossbow,
		/obj/item/weldingtool/mini,
		/obj/item/megaphone/command,
		/obj/item/paint/anycolor/cyborg,
		/obj/item/soap/nanotrasen/cyborg,
		/obj/item/borg/cyborghug/medical,
		/obj/item/borg/lollipop,
		/obj/item/reagent_containers/borghypo/centcom,
		/obj/item/extinguisher/mini,
		/obj/item/borg/apparatus/paper_manipulator,
		/obj/item/screwdriver/cyborg,
		/obj/item/crowbar/cyborg,
		/obj/item/picket_sign/cyborg,
		/obj/item/borg/stun,
	)
	radio_channels = list(RADIO_CHANNEL_CENTCOM, RADIO_CHANNEL_COMMAND)
	model_traits = list(TRAIT_PUSHIMMUNE, TRAIT_NOFLASH)
	emag_modules = list(
		/obj/item/reagent_containers/spray/cyborg_lube,
		/obj/item/paperplane/syndicate/hardlight
	)
	special_light_key = null
	borg_skins = list(
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_CENTCOM_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		), //aKhroma :)
		"Vale" = list(
			SKIN_ICON_STATE = "vale",
			SKIN_ICON = CYBORG_ICON_CENTCOM_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE)
		),
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
		SKIN_ICON = CYBORG_ICON_CC_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
	)

/obj/item/robot_model/centcom/rebuild_modules()
	..()
	var/mob/living/silicon/robot/cyborg = loc
	cyborg.scrambledcodes = TRUE
	cyborg.req_access = list(ACCESS_CENT_GENERAL)
	cyborg.faction |= ROLE_DEATHSQUAD //You're part of CENTCOM now

/obj/item/robot_model/centcom/remove_module(obj/item/removed_module, delete_after)
	..()
	var/mob/living/silicon/robot/cyborg = loc
	cyborg.scrambledcodes = FALSE
	cyborg.req_access = list(ACCESS_ROBOTICS)
	cyborg.faction -= ROLE_DEATHSQUAD //You're no longer part of CENTCOM

/* Research cyborgs */

/obj/item/robot_model/sci
	name = "Research"
	basic_modules = list(
		/obj/item/assembly/flash/cyborg,
		/obj/item/extinguisher,
		/obj/item/weldingtool/largetank/cyborg,
		/obj/item/borg/cyborg_omnitool/research, // A modded engineering omitool.
		/obj/item/borg/cyborghug/medical, // You can now hug and fix synths :3c
		/obj/item/multitool/cyborg,
		/obj/item/screwdriver/cyborg/power,
		/obj/item/crowbar/cyborg/power,
		/obj/item/analyzer,
		/obj/item/assembly/signaler/cyborg,
		/obj/item/borg/apparatus/sheet_manipulator,
		/obj/item/storage/bag/sheetsnatcher/borg,
		/obj/item/storage/bag/xeno,
		/obj/item/stack/cable_coil,
		/obj/item/borg/apparatus/beaker,
		/obj/item/borg/apparatus/organ_storage,
		/obj/item/borg/apparatus/research,
		/obj/item/borg/apparatus/circuit_sci,
		/obj/item/storage/part_replacer/cyborg,
		/obj/item/healthanalyzer,
		/obj/item/experi_scanner,
		/obj/item/stack/medical/gauze,
		/obj/item/borg/apparatus/tank_manipulator,
	)
	radio_channels = list(RADIO_CHANNEL_SCIENCE)

	emag_modules = list(
		/obj/item/borg/stun,
		/obj/item/experimental_dash,
		/obj/item/borg/apparatus/illegal //Get to work unit!
	)
	cyborg_base_icon = "research"
	cyborg_icon_override = CYBORG_ICON_SCI
	model_select_icon = "research"
	model_select_alternate_icon = 'modular_zubbers/code/modules/silicons/borgs/sprites/screen_robot.dmi'
	model_traits = list(TRAIT_KNOW_ROBO_WIRES, TRAIT_RESEARCH_CYBORG)
	borg_skins = list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_SCI_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		"Vale" = list(
			SKIN_ICON_STATE = "vale",
			SKIN_ICON = CYBORG_ICON_SCI_WIDE,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			VALE_HAT_OFFSET
		),
		"Borgi" = list(
			SKIN_ICON_STATE = "borgi",
			SKIN_ICON = CYBORG_ICON_SCI_WIDE,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			BORGI_HAT_OFFSET
		),
		"Hound" = list(
			SKIN_ICON_STATE = "hound",
			SKIN_ICON = CYBORG_ICON_SCI_WIDE,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"DarkHound" = list(
			SKIN_ICON_STATE = "hounddark",
			SKIN_ICON = CYBORG_ICON_SCI_WIDE,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"Drake" = list(
			SKIN_ICON_STATE = "drake",
			SKIN_ICON = CYBORG_ICON_SCI_WIDE,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			DRAKE_HAT_OFFSET
		),
		"Zoomba" = list(
			SKIN_ICON_STATE = "zoomba",
			SKIN_ICON = CYBORG_ICON_SCI,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL),
			ZOOMBA_HAT_OFFSET,
		),
		"Eyebot" = list(
			SKIN_ICON_STATE = "eyebot",
			SKIN_ICON = CYBORG_ICON_SCI,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL),
		),
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_SCI_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"Meka" = list(
			SKIN_ICON_STATE = "mekasci",
			SKIN_ICON = CYBORG_ICON_SCI_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL), TALL_HAT_OFFSET
		),
		"NiKA" = list(
			SKIN_ICON_STATE = "fmekasci",
			SKIN_ICON = CYBORG_ICON_SCI_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL), TALL_HAT_OFFSET
		),
		"NiKO" = list(
			SKIN_ICON_STATE = "mmekasci",
			SKIN_ICON = CYBORG_ICON_SCI_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL), TALL_HAT_OFFSET
		),
		"NiKO (Alt)" = list(
			SKIN_ICON_STATE = "sfmekasci",
			SKIN_ICON = CYBORG_ICON_SCI_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL), TALL_HAT_OFFSET
		),
		"K4T (Research)" = list(
			SKIN_ICON_STATE = "k4tsci",
			SKIN_ICON = CYBORG_ICON_SCI_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL), TALL_HAT_OFFSET
		),
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
		SKIN_ICON = CYBORG_ICON_SCI_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahansci",
			SKIN_ICON = CYBORG_ICON_SCI_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "haydeesci",
			SKIN_ICON = CYBORG_ICON_SCI_HAYDEE_BUBBER,
		),
		"K1-T7Y" = list(
			SKIN_ICON_STATE = "sci",
			SKIN_ICON = CYBORG_ICON_SCI_KITTYBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE, TRAIT_R_SMALL),
		),
		"C9-T7O" = list(
			SKIN_ICON_STATE = "sci",
			SKIN_ICON = CYBORG_ICON_SCI_CATBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-sci",
			SKIN_ICON = CYBORG_ICON_SCI_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-sci",
			SKIN_ICON = CYBORG_ICON_SCI_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
	)


/* BUBBER SPRITE ADDITIONS BELOW */

// Clown borgs
/obj/item/robot_model/clown/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"Vale" = list(
			SKIN_ICON_STATE = "vale",
			SKIN_ICON = CYBORG_ICON_CLOWN_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanclown",
			SKIN_ICON = CYBORG_ICON_CLOWN_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurclown",
			SKIN_ICON = CYBORG_ICON_CLOWN_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-clown",
			SKIN_ICON = CYBORG_ICON_CLOWN_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Standard borgs
/obj/item/robot_model/standard/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_GEN_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
		SKIN_ICON = CYBORG_ICON_GEN_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
	)

// Medical borgs
/obj/item/robot_model/medical/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_MED_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_MED_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
		SKIN_ICON = CYBORG_ICON_MED_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanmed",
			SKIN_ICON = CYBORG_ICON_MED_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurmed",
			SKIN_ICON = CYBORG_ICON_MED_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeMedFix",
			SKIN_ICON = CYBORG_ICON_MED_HAYDEE_BUBBER,
		),
		"NiKO (Alt)" = list(
			SKIN_ICON_STATE = "sfmekamed",
			SKIN_ICON = CYBORG_ICON_MED_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET
		),
		"K1-T7Y" = list(
			SKIN_ICON_STATE = "medicat",
			SKIN_ICON = CYBORG_ICON_MED_KITTYBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE, TRAIT_R_SMALL),
		),
		"C9-T7O" = list(
			SKIN_ICON_STATE = "meowdical",
			SKIN_ICON = CYBORG_ICON_MED_CATBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-med",
			SKIN_ICON = CYBORG_ICON_MED_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-med",
			SKIN_ICON = CYBORG_ICON_MEDICAL_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Engineering borgs
/obj/item/robot_model/engineering/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_ENG_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_ENG_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
		SKIN_ICON = CYBORG_ICON_ENG_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahaneng",
			SKIN_ICON = CYBORG_ICON_ENG_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaureng",
			SKIN_ICON = CYBORG_ICON_ENG_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "haydeeengineclassic",
			SKIN_ICON = CYBORG_ICON_ENG_HAYDEE_BUBBER,
		),
		"NiKO (Alt)" = list(
			SKIN_ICON_STATE = "sfmekaengi",
			SKIN_ICON = CYBORG_ICON_ENG_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET
		),
		"K1-T7Y" = list(
			SKIN_ICON_STATE = "engi",
			SKIN_ICON = CYBORG_ICON_ENG_KITTYBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE, TRAIT_R_SMALL),
		),
		"C9-T7O" = list(
			SKIN_ICON_STATE = "engi",
			SKIN_ICON = CYBORG_ICON_ENG_CATBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-engi",
			SKIN_ICON = CYBORG_ICON_ENGI_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-engi",
			SKIN_ICON = CYBORG_ICON_ENGI_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Jani borgs
/obj/item/robot_model/janitor/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_JANI_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		//64x48 sprites below (Raptor)
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_JANI_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR_ALT,
		SKIN_ICON = CYBORG_ICON_SERV_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanjani",
			SKIN_ICON = CYBORG_ICON_JANI_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurjani",
			SKIN_ICON = CYBORG_ICON_JANI_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeJannieClassic",
			SKIN_ICON = CYBORG_ICON_JANI_HAYDEE_BUBBER,
		),
		"K1-T7Y" = list(
			SKIN_ICON_STATE = "jani",
			SKIN_ICON = CYBORG_ICON_JANI_KITTYBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE, TRAIT_R_SMALL),
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-jani",
			SKIN_ICON = CYBORG_ICON_JANI_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-jani",
			SKIN_ICON = CYBORG_ICON_JANI_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Mining borgs
/obj/item/robot_model/miner/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_MINE_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		//64x32 Sprites below (Wide)
		"Corrupt" = list(
			SKIN_ICON_STATE = "corrupt",
			SKIN_ICON = CYBORG_ICON_MINING_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			CORRUPT_HAT_OFFSET
		),
		"Corrupt Alt" = list(
			SKIN_ICON_STATE = "corruptalt",
			SKIN_ICON = CYBORG_ICON_MINING_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			CORRUPT_HAT_OFFSET
		),
		"K1-T7Y" = list(
			SKIN_ICON_STATE = "mining",
			SKIN_ICON = CYBORG_ICON_MINE_KITTYBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE, TRAIT_R_SMALL),
		),
		"C9-T7O" = list(
			SKIN_ICON_STATE = "mining",
			SKIN_ICON = CYBORG_ICON_MINE_CATBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		//64x48 sprites below (Raptor)
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_MINING_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
		SKIN_ICON = CYBORG_ICON_MIN_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanmine",
			SKIN_ICON = CYBORG_ICON_MINING_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurmine",
			SKIN_ICON = CYBORG_ICON_MINING_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeMinerClassic",
			SKIN_ICON = CYBORG_ICON_MINING_HAYDEE_BUBBER,
		),
		"NiKA (Alt)" = list(
			SKIN_ICON_STATE = "sfmekamine",
			SKIN_ICON = CYBORG_ICON_MINING_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-mine",
			SKIN_ICON = CYBORG_ICON_MINING_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-mining",
			SKIN_ICON = CYBORG_ICON_MINING_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Security borgs
/obj/item/robot_model/security/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_SEC_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		//64x32 Sprites below (Wide)
		"K1-T7Y" = list(
			SKIN_ICON_STATE = "sec",
			SKIN_ICON = CYBORG_ICON_SEC_KITTYBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE, TRAIT_R_SMALL),
		),
		"C9-T7O" = list(
			SKIN_ICON_STATE = "sec",
			SKIN_ICON = CYBORG_ICON_SEC_CATBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_SEC_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"SmolRaptor BLU" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR_ALT,
			SKIN_ICON = CYBORG_ICON_SEC_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		//32x64 Sprites below (Tall)
		"Meka - Bluesec" = list(
			SKIN_ICON_STATE = "mekasecalt",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahansec",
			SKIN_ICON = CYBORG_ICON_SEC_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		//64x48 sprites below (Raptor)
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_SEC_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-sec",
			SKIN_ICON = CYBORG_ICON_SEC_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-sec",
			SKIN_ICON = CYBORG_ICON_SEC_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Peacekeeper borgs
/obj/item/robot_model/peacekeeper/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_PK_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		//32x64 Sprites below (Tall)
		"Meka - Bluesec" = list(
			SKIN_ICON_STATE = "mekasecalt",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET,
		),
		"Foxtrot - Peacekeeper" = list(
			//Sprites by Crumpaloo!
			SKIN_ICON_STATE = "ftpeace",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET,
		),
		//64x32 Sprites below (Wide)
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_PK_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanpeace",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurpeace",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeePeaceClassic",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_HAYDEE_BUBBER,
		),
		"Hound" = list(
			SKIN_ICON_STATE = "pkhound",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"NiKO (Alt)" = list(
			SKIN_ICON_STATE = "sfmekapeace",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK,TRAIT_R_UNIQUETIP,TRAIT_R_TALL),
			TALL_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-pk",
			SKIN_ICON = CYBORG_ICON_PK_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-pk",
			SKIN_ICON = CYBORG_ICON_PEACEKEEPER_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Service borgs
/obj/item/robot_model/service/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_SERV_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		"Fancy Raptor" = list(
			SKIN_ICON_STATE = "fancyraptor",
			SKIN_ICON = CYBORG_ICON_SERVICE_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_SERV_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanserv",
			SKIN_ICON = CYBORG_ICON_SERVICE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanserv_alt",
			SKIN_ICON = CYBORG_ICON_SERVICE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurserv",
			SKIN_ICON = CYBORG_ICON_SERVICE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeSlutviceClassic",
			SKIN_ICON = CYBORG_ICON_SERVICE_HAYDEE_BUBBER,
		),
		"Bundee" = list(
			SKIN_ICON_STATE = "HaydeeBunviceClassic",
			SKIN_ICON = CYBORG_ICON_SERVICE_BUNDEE_BUBBER,
		),
		"Hound" = list(
			SKIN_ICON_STATE = "servhound",
			SKIN_ICON = CYBORG_ICON_SERVICE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"NiKO (Alt)" = list(
			SKIN_ICON_STATE = "sfmekaserv",
			SKIN_ICON = CYBORG_ICON_SERVICE_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET
		),
		"K1-T7Y" = list(
			SKIN_ICON_STATE = "service",
			SKIN_ICON = CYBORG_ICON_SERV_KITTYBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE, TRAIT_R_SMALL),
		),
		"C9-T7O" = list(
			SKIN_ICON_STATE = "service",
			SKIN_ICON = CYBORG_ICON_SERV_CATBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-serv",
			SKIN_ICON = CYBORG_ICON_SERVICE_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-serv",
			SKIN_ICON = CYBORG_ICON_SERV_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Cargo borgs
/obj/item/robot_model/cargo/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"SmolRaptor" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
		SKIN_ICON = CYBORG_ICON_CAR_SMOLRAPTOR,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
		SMOL_RAPTOR_HAT_OFFSET
		),
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_CAR_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL, TRAIT_R_LIGHT_WEIGHT),
		F3LINE_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahancargo",
			SKIN_ICON = CYBORG_ICON_CARGO_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurcargo",
			SKIN_ICON = CYBORG_ICON_CARGO_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"NiKO (Alt)" = list(
			SKIN_ICON_STATE = "sfmekacargo",
			SKIN_ICON = CYBORG_ICON_CARGO_TALL,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			TALL_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-cargo",
			SKIN_ICON = CYBORG_ICON_CARGO_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-cargo",
			SKIN_ICON = CYBORG_ICON_CARGO_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
		"Wage Cage" = list(SKIN_ICON_STATE = CYBORG_ICON_TYPE_WAGECAGE,
			SKIN_ICON = CYBORG_ICON_CARGO_WAGECAGE,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_TALL),
			WAGECAGE_HAT_OFFSET
		),
	)

// Syndicate jack borgs
/obj/item/robot_model/syndicatejack/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"Vale" = list(
			SKIN_ICON_STATE = "vale",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			VALE_HAT_OFFSET
		),
		"Pupdozer" = list(
			SKIN_ICON_STATE = "pupdozer",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_WIDE)
		),
		"Saboraptor" = list(
			SKIN_ICON_STATE = "Saboraptor",
			SKIN_ICON = CYBORG_ICON_SYNDIE_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Mediraptor" = list(
			SKIN_ICON_STATE = "Mediraptor",
			SKIN_ICON = CYBORG_ICON_SYNDIE_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Mechraptor" = list(
			SKIN_ICON_STATE = "Mechraptor",
			SKIN_ICON = CYBORG_ICON_SYNDIE_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_SYNDI_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL),
		F3LINE_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahansyndi",
			SKIN_ICON = CYBORG_ICON_SYNDIE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaursyndi",
			SKIN_ICON = CYBORG_ICON_SYNDIE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeSecClassic",
			SKIN_ICON = CYBORG_ICON_SYNDIE_HAYDEE_BUBBER,
		),
		"Hound" = list(
			SKIN_ICON_STATE = "syndiehound",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_SYN_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Syndicate borgs
/obj/item/robot_model/syndicate
	borg_skins = list(
		//DEFAULT MEDICAL MODULE
		"Syndicate Medical" = list(
			SKIN_ICON_STATE = "synd_sec",
			SKIN_ICON = 'icons/mob/silicon/robots.dmi'
		),
		"Saboraptor" = list(
			SKIN_ICON_STATE = "Saboraptor",
			SKIN_ICON = CYBORG_ICON_SYNDIE_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"Vale" = list(
			SKIN_ICON_STATE = "vale",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_SYNDI_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL),
		F3LINE_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahansyndi",
			SKIN_ICON = CYBORG_ICON_SYNDIE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeSecClassic",
			SKIN_ICON = CYBORG_ICON_SYNDIE_HAYDEE_BUBBER,
		),
		"Hound" = list(
			SKIN_ICON_STATE = "syndiehound",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_SYN_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Syndicate medical borgs
/obj/item/robot_model/syndicate_medical
	borg_skins = list(
		//DEFAULT MEDICAL MODULE
		"Syndicate Medical" = list(
			SKIN_ICON_STATE = "synd_medical",
			SKIN_ICON = 'icons/mob/silicon/robots.dmi'
		),
		//64x64 (Largerobot) Sprites Below
		"Mediraptor" = list(
			SKIN_ICON_STATE = "Mediraptor",
			SKIN_ICON = CYBORG_ICON_SYNDIE_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		//64x32 (Widerobot) Sprites Below
		"Vale" = list(
			SKIN_ICON_STATE = "vale",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_SYNDI_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL),
		F3LINE_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahansyndi",
			SKIN_ICON = CYBORG_ICON_SYNDIE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeSecClassic",
			SKIN_ICON = CYBORG_ICON_SYNDIE_HAYDEE_BUBBER,
		),
		"Hound" = list(
			SKIN_ICON_STATE = "syndiehound",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_SYN_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Syndicate Saboteur borgs
/obj/item/robot_model/saboteur
	borg_skins = list(
		//DEFAULT SABOTEUR MODULE
		"Syndicate Engi" = list(
			SKIN_ICON_STATE = "synd_engi",
			SKIN_ICON = 'icons/mob/silicon/robots.dmi',
		),
		//64x64 (Largerobot) Sprites Below
		"Mechraptor" = list(
			SKIN_ICON_STATE = "Mechraptor",
			SKIN_ICON = CYBORG_ICON_SYNDIE_LARGE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
		),
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_SYNDI_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL),
		F3LINE_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahansyndi",
			SKIN_ICON = CYBORG_ICON_SYNDIE_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Haydee" = list(
			SKIN_ICON_STATE = "HaydeeSecClassic",
			SKIN_ICON = CYBORG_ICON_SYNDIE_HAYDEE_BUBBER,
		),
		//64x32 (Widerobot) Sprites Below
		"Hound" = list(
			SKIN_ICON_STATE = "syndiehound",
			SKIN_ICON = CYBORG_ICON_SYNDIE_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			HOUND_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_SYN_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-syndi",
			SKIN_ICON = CYBORG_ICON_SYNDI_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Ninja borgs
/obj/item/robot_model/ninja/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		/*
		"Raptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_RAPTOR,
			SKIN_ICON = CYBORG_ICON_NINJA_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE),
			RAPTOR_HAT_OFFSET
		),
		"Vale" = list(
			SKIN_ICON_STATE = "valeninja",
			SKIN_ICON = CYBORG_ICON_NINJA_WIDE_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_WIDE)
		),
		*/
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_NINJA_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL),
		F3LINE_HAT_OFFSET
		),
		"Dullahan" = list(
			SKIN_ICON_STATE = "dullahanninja",
			SKIN_ICON = CYBORG_ICON_NINJA_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL),
			DULLAHAN_HAT_OFFSET
		),
		"Dullahan (Taur)" = list(
			SKIN_ICON_STATE = "dullahantaurninja",
			SKIN_ICON = CYBORG_ICON_NINJA_TALL_BUBBER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUETIP, TRAIT_R_TALL, TRAIT_R_UNIQUEPANEL),
			DULLAHAN_TAUR_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_NIN_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-ninja",
			SKIN_ICON = CYBORG_ICON_NINJA_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-ninja",
			SKIN_ICON = CYBORG_ICON_NINJA_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)

// Ninja Saboteur borgs
/obj/item/robot_model/ninja_saboteur/Initialize(mapload)
	. = ..()
	borg_skins |= list(
		"F3-LINE" = list(
		SKIN_ICON_STATE = CYBORG_ICON_STATE_NINJA_FELI,
		SKIN_ICON = CYBORG_ICON_ALL_FELI,
		SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SQUADRUPED, TRAIT_R_SMALL),
		F3LINE_HAT_OFFSET
		),
		"SmolRaptor" = list(
			SKIN_ICON_STATE = CYBORG_ICON_TYPE_SMOLRAPTOR,
			SKIN_ICON = CYBORG_ICON_NIN_SMOLRAPTOR,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_SMALL, TRAIT_R_WIDE),
			SMOL_RAPTOR_HAT_OFFSET
		),
		"Myomer" = list(
			SKIN_ICON_STATE = "myomer-ninja",
			SKIN_ICON = CYBORG_ICON_NINJA_MYOMER,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEPANEL, TRAIT_R_WIDE, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS),
			MYOMER_HAT_OFFSET
		),
		"Dragon" = list(
			SKIN_ICON_STATE = "dragon-ninja",
			SKIN_ICON = CYBORG_ICON_NINJA_DRAGONBORG,
			SKIN_FEATURES = list(TRAIT_R_UNIQUEWRECK, TRAIT_R_UNIQUEPANEL, TRAIT_R_HAS_UNIQUE_RESTING_LIGHTS, TRAIT_R_EXPANDER_BLOCKED, TRAIT_R_BIG)
		),
	)
