template = "bitmask/diagonal_32x32.toml"

# When we cut up our blocks, we're cutting "around" a central point
# We typically want to cut around the upper center for baylike walls, so let's do that here
[cut_pos]
x = 16
y = 5
