#define MOONSTATION_ATMOS GAS_O2 + "=20.2;" + GAS_N2 + "=78.5;" + GAS_CO2 + "=4.6;" + GAS_WATER_VAPOR + "=1.1;TEMP=347.65"
#define MOONSTATION_ATMOS_CAVE LAVALAND_DEFAULT_ATMOS

#define ZTRAIT_SANDSTORM "Weather_Sandstorm"
#define ZTRAIT_MOONSTATION_RUINS "Moonstation Ruins"
