#define SCENE_ASSISTANT_RANGE 3
#define SCENE_ASSISTANT_MAX_CHARS 2000
#define SCENE_ASSISTANT_MAX_LOG 250
#define SCENE_ASSISTANT_INVITE_TIMEOUT (2 MINUTES)
#define SCENE_ASSISTANT_RANGE_CHECK_INTERVAL (5 SECONDS)
#define SCENE_ASSISTANT_INTERACTION_CACHE (2 SECONDS)
#define SCENE_ASSISTANT_NEARBY_CACHE (1 SECONDS)
