#define ui_thirst "EAST-1:2,CENTER:21"

// Thirst
#define THIRST_LEVEL_THRESHOLD		800
#define THIRST_LEVEL_VERY_QUENCHED	600
#define THIRST_LEVEL_QUENCHED		450
#define THIRST_LEVEL_BIT_THIRSTY	350
#define THIRST_LEVEL_THIRSTY		250
#define THIRST_LEVEL_PARCHED		150

// Start Level
#define THIRST_LEVEL_START_MIN	400
#define THIRST_LEVEL_START_MAX	500

/// Factor
#define THIRST_FACTOR 0.06

// Trait For Species
#define TRAIT_NOTHIRST "no_thirst"
