name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    runs-on: ubuntu-24.04
    outputs:
      staled_prs: ${{ steps.filter-prs.outputs.result }}

    steps:
      - name: Mark stale issues and pull requests
        uses: actions/stale@v10
        id: stale
        with:
          repo-token: ${{ secrets.BUBBERBOT_PAT }}
          stale-pr-message: "This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself"
          days-before-stale: 14
          days-before-close: 21
          stale-pr-label: "Stale"
          days-before-issue-stale: -1
          stale-issue-label: "Cleanup Flagged"
          remove-issue-stale-when-updated: false
          exempt-pr-labels: "Stale-b-Gone,Good First PR"
          operations-per-run: 300
      - name: Filter staled pull requests for announcement
        id: filter-prs
        uses: actions/github-script@v9
        with:
          script: |
            return JSON.parse(`${{steps.stale.outputs.staled-issues-prs}}`)
                       .filter(issue => !!issue.pull_request)
                       .map(pr => ({
                        title: pr.title,
                        number: pr.number,
                        html_url: pr.pull_request.html_url,
                       }));

  announce:
    runs-on: ubuntu-24.04
    needs: stale
    if: ${{ needs.stale.outputs.staled_prs != '[]' }}
    strategy:
      matrix:
        pull_request: ${{ fromJSON(needs.stale.outputs.staled_prs) }}
    steps:
      - name: "Check for DISCORD_WEBHOOK"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
      - name: Send Discord notification
        uses: tgstation/discord-notify@v3
        if: >
          steps.secrets_set.outputs.SECRETS_ENABLED
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ matrix.pull_request.title }}
          message: ${{ format('**Pull Request \#{0} automatically marked as stale.**', matrix.pull_request.number) }}
          include_image: false
          show_author: false
          avatar_url: https://avatars.githubusercontent.com/u/1363778?s=200&v=4
          username: GitHub
          title_url: "${{ matrix.pull_request.html_url }}"
